### ISSUE TITLE
A java Exception occurred in the process

### ISSUE THREAD

**Issue by Dunked0n** [ueberdosis/mouseless#21]
Uncaught Exception:
TypeError: Cannot read property 'isDestroyed' of undefined
at Object.isWindowVisible (/Applications/Mouseless.app/Contents/Resources/app.asar/background.js:2:298319)
at Function.<anonymous> (/Applications/Mouseless.app/Contents/Resources/app.asar/background.js:2:298597)

steps to reproduce:
Press the reference shortcut while in safari

**Comment by DigitalGreyHat** [comment]
btw: this is not a Java error, it is a JavaScript error!

**Comment by svenadlung** [comment]
@S0ulf3re could you explain what exactly "reference shortcut" means or what key combination it is?
